# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exchanger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edgars Beigarts"]
  s.date = %q{2010-08-30}
  s.description = %q{Ruby library for accessing Microsoft Exchange using Exchange Web Services}
  s.email = %q{1@wb4.lv}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "lib/exchanger.rb",
     "lib/exchanger/attributes.rb",
     "lib/exchanger/boolean.rb",
     "lib/exchanger/client.rb",
     "lib/exchanger/config.rb",
     "lib/exchanger/dirty.rb",
     "lib/exchanger/element.rb",
     "lib/exchanger/elements/attendee.rb",
     "lib/exchanger/elements/base_folder.rb",
     "lib/exchanger/elements/calendar_folder.rb",
     "lib/exchanger/elements/calendar_item.rb",
     "lib/exchanger/elements/complete_name.rb",
     "lib/exchanger/elements/contact.rb",
     "lib/exchanger/elements/contacts_folder.rb",
     "lib/exchanger/elements/distribution_list.rb",
     "lib/exchanger/elements/email_address.rb",
     "lib/exchanger/elements/entry.rb",
     "lib/exchanger/elements/folder.rb",
     "lib/exchanger/elements/identifier.rb",
     "lib/exchanger/elements/im_address.rb",
     "lib/exchanger/elements/item.rb",
     "lib/exchanger/elements/mailbox.rb",
     "lib/exchanger/elements/meeting_cancellation.rb",
     "lib/exchanger/elements/meeting_message.rb",
     "lib/exchanger/elements/meeting_request.rb",
     "lib/exchanger/elements/meeting_response.rb",
     "lib/exchanger/elements/message.rb",
     "lib/exchanger/elements/phone_number.rb",
     "lib/exchanger/elements/physical_address.rb",
     "lib/exchanger/elements/search_folder.rb",
     "lib/exchanger/elements/single_recipient.rb",
     "lib/exchanger/elements/task.rb",
     "lib/exchanger/elements/tasks_folder.rb",
     "lib/exchanger/field.rb",
     "lib/exchanger/operation.rb",
     "lib/exchanger/operations/create_item.rb",
     "lib/exchanger/operations/find_folder.rb",
     "lib/exchanger/operations/find_item.rb",
     "lib/exchanger/operations/get_folder.rb",
     "lib/exchanger/operations/get_item.rb",
     "lib/exchanger/operations/update_item.rb",
     "lib/exchanger/persistence.rb"
  ]
  s.homepage = %q{http://github.com/ebeigarts/exchanger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby library for accessing Microsoft Exchange using Exchange Web Services}
  s.test_files = [
    "spec/calendar_item_spec.rb",
     "spec/client_spec.rb",
     "spec/contact_spec.rb",
     "spec/element_spec.rb",
     "spec/field_spec.rb",
     "spec/folder_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.2.2"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<httpclient>, [">= 2.1.5.2"])
      s.add_runtime_dependency(%q<rubyntlm>, [">= 0.1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.2.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.0"])
      s.add_dependency(%q<httpclient>, [">= 2.1.5.2"])
      s.add_dependency(%q<rubyntlm>, [">= 0.1.1"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.2.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.0"])
    s.add_dependency(%q<httpclient>, [">= 2.1.5.2"])
    s.add_dependency(%q<rubyntlm>, [">= 0.1.1"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

