---
http_interactions:
- request:
    method: post
    uri: https://amsprd0710.outlook.com/EWS/Exchange.asmx
    body:
      encoding: UTF-8
      string: |
        <?xml version="1.0"?>
        <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GetUserConfiguration xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
              <UserConfigurationName Name="CategoryList">
                <t:FolderId Id="AAAkAG91dGxvb2tfNTY3NDUzNUY3QTY0QjIwMUBvdXRsb29rLmNvbQAuAAAAAAC11EXZT+3TSZbZG9cMT+XoAQAdX+/tTQhGSJ2g6HFKPliuAAAAAAENAAA="/>
              </UserConfigurationName>
              <UserConfigurationProperties>All</UserConfigurationProperties>
            </GetUserConfiguration>
          </soap:Body>
        </soap:Envelope>
    headers:
      User-Agent:
      - HTTPClient/1.0 (2.8.3, ruby 2.7.0 (2019-12-25))
      Accept:
      - "*/*"
      Date:
      - Tue, 07 Apr 2020 09:24:48 GMT
      Soapaction:
      - http://schemas.microsoft.com/exchange/services/2006/messages/GetUserConfiguration
      Content-Type:
      - text/xml; charset=utf-8
      Authorization:
      - Basic bWljaGFlbEBsaXR0b24uc2U6MTI4MHNhaWw=
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - private
      Transfer-Encoding:
      - chunked
      Content-Type:
      - text/xml; charset=utf-8
      Server:
      - Microsoft-IIS/10.0
      Request-Id:
      - 873b10f6-7b19-450c-99d3-007b22fbc782
      X-Calculatedfetarget:
      - PR0P264CU008.internal.outlook.com
      X-Backendhttpstatus:
      - '200'
      - '200'
      Set-Cookie:
      - exchangecookie=ef22dea0228e46bebddd7e688cf53017; expires=Wed, 07-Apr-2021
        09:24:48 GMT; path=/; secure; HttpOnly
      X-Feproxyinfo:
      - PR0P264CA0189.FRAP264.PROD.OUTLOOK.COM
      X-Calculatedbetarget:
      - AM7PR05MB6693.eurprd05.prod.outlook.com
      X-Rum-Validated:
      - '1'
      X-Ewshandler:
      - GetUserConfiguration
      X-Aspnet-Version:
      - 4.0.30319
      X-Besku:
      - WCS6
      X-Diaginfo:
      - AM7PR05MB6693
      X-Beserver:
      - AM7PR05MB6693
      X-Proxy-Routingcorrectness:
      - '1'
      X-Proxy-Backendserverstatus:
      - '200'
      X-Feserver:
      - HE1PR0101CA0021
      - PR0P264CA0189
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 07 Apr 2020 09:24:47 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo
        MajorVersion="15" MinorVersion="20" MajorBuildNumber="2878" MinorBuildNumber="21"
        xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:GetUserConfigurationResponse
        xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetUserConfigurationResponseMessage
        ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:UserConfiguration><t:UserConfigurationName
        Name="CategoryList"><t:FolderId Id="AAAkAG91dGxvb2tfNTY3NDUzNUY3QTY0QjIwMUBvdXRsb29rLmNvbQAuAAAAAAC11EXZT+3TSZbZG9cMT+XoAQAdX+/tTQhGSJ2g6HFKPliuAAAAAAENAAA="/></t:UserConfigurationName><t:ItemId
        Id="AAAkAG91dGxvb2tfNTY3NDUzNUY3QTY0QjIwMUBvdXRsb29rLmNvbQBGAAAAAAC11EXZT+3TSZbZG9cMT+XoBwAdX+/tTQhGSJ2g6HFKPliuAAAAAAENAAAdX+/tTQhGSJ2g6HFKPliuAAE+mM55AAA="
        ChangeKey="CQAAABYAAAAdX+/tTQhGSJ2g6HFKPliuAAE+wfB/"/><t:XmlData>77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48Y2F0ZWdvcmllcyBsYXN0U2F2ZWRUaW1lPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjE2ODAyOThaIiB4bWxucz0iQ2F0ZWdvcnlMaXN0LnhzZCI+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9IlLDtmQga2F0ZWdvcmkiIGNvbG9yPSIwIiBrZXlib2FyZFNob3J0Y3V0PSIwIiBsYXN0VGltZVVzZWROb3Rlcz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkSm91cm5hbD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkQ29udGFjdHM9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZFRhc2tzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRDYWxlbmRhcj0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkTWFpbD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBndWlkPSJ7OWFjNmIyMmEtOThlMS00MzMwLTg3NzctODM4Y2EwOTNhNTZmfSIgLz48Y2F0ZWdvcnkgcmVuYW1lT25GaXJzdFVzZT0iMSIgbmFtZT0iT3JhbmdlIGthdGVnb3JpIiBjb2xvcj0iMSIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgZ3VpZD0iezJlNGM2ZDZmLTRlODEtNDJhZS1iYTY2LTJkODJiM2MwNTE3Mn0iIC8+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9Ikd1bCBrYXRlZ29yaSIgY29sb3I9IjMiIGtleWJvYXJkU2hvcnRjdXQ9IjAiIGxhc3RUaW1lVXNlZE5vdGVzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRKb3VybmFsPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRDb250YWN0cz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkVGFza3M9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZENhbGVuZGFyPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRNYWlsPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWQ9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGd1aWQ9Ins2YTViMjAzZC0zODE0LTQzMTItOTlmNi0wODQ1NWU2NWM4M2N9IiAvPjxjYXRlZ29yeSByZW5hbWVPbkZpcnN0VXNlPSIxIiBuYW1lPSJHcsO2biBrYXRlZ29yaSIgY29sb3I9IjQiIGtleWJvYXJkU2hvcnRjdXQ9IjAiIGxhc3RUaW1lVXNlZE5vdGVzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRKb3VybmFsPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRDb250YWN0cz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkVGFza3M9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZENhbGVuZGFyPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRNYWlsPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWQ9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGd1aWQ9InsyNWI3MjU4Yi0zMzU0LTRkM2QtYWNjNC1mZWIwODlmYmFmNDB9IiAvPjxjYXRlZ29yeSByZW5hbWVPbkZpcnN0VXNlPSIxIiBuYW1lPSJCbMOlIGthdGVnb3JpIiBjb2xvcj0iNyIga2V5Ym9hcmRTaG9ydGN1dD0iMCIgbGFzdFRpbWVVc2VkTm90ZXM9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZEpvdXJuYWw9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZENvbnRhY3RzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRUYXNrcz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkQ2FsZW5kYXI9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZE1haWw9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgZ3VpZD0iezBhYzBjOThlLTM3NDgtNGRhMi1iNjc5LWU4MjIzMzZjMTM4NH0iIC8+PGNhdGVnb3J5IHJlbmFtZU9uRmlyc3RVc2U9IjEiIG5hbWU9IkxpbGEga2F0ZWdvcmkiIGNvbG9yPSI4IiBrZXlib2FyZFNob3J0Y3V0PSIwIiBsYXN0VGltZVVzZWROb3Rlcz0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkSm91cm5hbD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkQ29udGFjdHM9IjIwMTgtMDItMDRUMTU6MDI6NDYuMDU4NjQ5M1oiIGxhc3RUaW1lVXNlZFRhc2tzPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBsYXN0VGltZVVzZWRDYWxlbmRhcj0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkTWFpbD0iMjAxOC0wMi0wNFQxNTowMjo0Ni4wNTg2NDkzWiIgbGFzdFRpbWVVc2VkPSIyMDE4LTAyLTA0VDE1OjAyOjQ2LjA1ODY0OTNaIiBndWlkPSJ7ZjAzYzNkNmUtOTY4OS00MjJhLTg5YTMtZTJiZTM5NzBhMGYyfSIgLz48L2NhdGVnb3JpZXM+</t:XmlData></m:UserConfiguration></m:GetUserConfigurationResponseMessage></m:ResponseMessages></m:GetUserConfigurationResponse></s:Body></s:Envelope>
    http_version: 
  recorded_at: Tue, 07 Apr 2020 09:24:48 GMT
recorded_with: VCR 3.0.3
